### PR TITLE
Set-up basic structure

### PR DESCRIPTION
**Pull request by anhtin**
This sets up the basic structure of the project, closing #8. I've taken the liberty to choose a couple of libraries of my liking, but I'm open for discussion if there are a more fitting alternative.

## Why @reach/router?
The reason for choosing to use @reach/router instead of react-router is due to its minimalistic approach and simpler API. The latter has a lot of features that we'll never use, e.g. HashRouter, MemoryRouter, and StaticRouter, and requires a lot more code to achieve the same as can be achieved with @reach/router — for typical usages.

## Why styled-components?
The reason for choosing to use styled-components instead of "normal" CSS or CSS Modules is because the former allows for more re-usability:

* It has a theme feature built-in, which allows us to easily iterate on the theming without having to change large parts of the code, if used properly. Additionally, the theming feature allows us to easily swap out themes, if we happen to need support for multiple themes in the future. Sass would allow us to have a similar theming feature, but it lack scoping features as described below.

* It scopes styling to a specific component, which allows us to freely create styling without worrying about name collisions and how various the CSS of various components might affect one another. Although CSS Modules has this feature, it lacks a way to theming features as described above — its possible to use CSS variables, but browser support is an issue then.

* It supports composition, which if used correctly allows us to easily override or extending styling of styled-components. If we also avoid using CSS classes, which is easy with styled-components, we'll be able to override styling without having to worry about CSS precedence.

In addition to the above, styled-components also allow for more flexible CSS since it allows us to dynamically resolve styling based on React props.

### CODE REVIEW

**Review by LERoise — COMMENTED** [review]
Very good and descriptive PR, the code and changes looks good, i dont have any to say against the "package choices"

**Review by martinAtItera — APPROVED** [review]

**Review by martinothamar — APPROVED** [review]
Nice! Short bit in the readme about how to start developing? (i.e. is it just `npm start` or something else). Should we have an editorconfig for tab/spacing and other stuff to ensure we get consistent styling? I see `.prettierrc` is there so do you recommend VSCode with the prettier extension or does it just work out of the box?

**Comment by martinothamar** [comment]
Wooop I see there are details in the Wiki, nvm :)

**Review by LERoise — APPROVED** [review]

**Comment by anhtin** [comment]
We might actually consider adding a git hook that looks for linter and formatting errors on commit and fails if there are any.

**Pull request merged**
